title: 我的課程平台
theme: jekyll-theme-architect

collections:
  matlab:
    output: true
    permalink: /matlab/:name
  ai:
    output: true
    permalink: /ai/:name
  cpp:
    output: true
    permalink: /cpp/:name


